# Standard Library
## Problem 1

In [8]:
def func(L):
    print("min =", min(L),"max = ", max(L),"average =", (sum(L)/len(L)))

In [9]:
func([1, 2, 3])

min = 1 max =  3 average = 2.0


## Problem 2

In [11]:
a = int(1.1)
b = a
b = 1.1
a == b

False

In [4]:
print(a, b)   # only b changed. int is immutable

1 1.1


In [5]:
c = 'Happy New Year'
d = c
d = 12345
c == d

False

In [6]:
print([c, d])
type(c)

['Happy New Year', 12345]


str

In [7]:
type(d) #Only one changes. str is immutable

int

In [8]:
e = list(['a', 1])
f = e
f[0]= list([1, 2])
e == f

True

In [9]:
print(e, f) #Both changed. list is mutable

[[1, 2], 1] [[1, 2], 1]


In [10]:
g = (1, 2, 3, 4)
h = g
h += ('5',)
h == g

False

In [11]:
print(h, g) #only one changed. tuple is immutable

(1, 2, 3, 4, '5') (1, 2, 3, 4)


In [12]:
i = {1, 2, 3}
j = i
j -= {1}
j == i

True

In [13]:
print(i, j) #Both changed. set is mutable

{2, 3} {2, 3}


## Problem 3

In [17]:
import calculator as calc
def funcH(m, n):
    alpha = calc.funcP(m, m)
    beta = calc.funcP(n, n)
    print(calc.sqrt(calc.funcS(alpha, beta)))
m = 5
n = 12
funcH(m, n)

13.0


# Introduction to NumPy
## Problem 1

In [18]:
import numpy as np
def prod(A, B):
    return np.dot(np.array(A), np.array(B))

In [19]:
A = [[3, -1, 4], [1, 5, -9]]
B = [[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]]
prod(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [20]:
import numpy as np
def func(A):
    A = np.array(A)
    R = (-A * A * A) + (9 * A * A) - (15 * A)
    return R

In [21]:
A = [[3, 1, 4], [1, 5, 9], [-5, 3, 1]]
func(A)

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

## Problem 5

In [3]:
import numpy as np
def blockmat(A, B, C):
    A = np.array(A)
    B = np.array(B)
    C = np.array(C)
    row1 = np.column_stack((np.zeros((3,3)), A.T, np.eye((3))))
    row2 = np.column_stack((A, np.zeros((2, 2)), np.zeros((2, 3))))
    row3 = np.column_stack((B, np.zeros((3,2)), C))
    print(np.vstack((row1, row2, row3)))

In [5]:
A = [[0, 2, 4], [1, 3, 5]]
B = [[3, 0, 0], [3, 3, 0], [3, 3, 3]]
C = [[-2, 0, 0], [0, -2, 0], [0, 0, -2]]
blockmat(A, B, C)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


# Object-Oriented Programming
## Problem 1

In [20]:
class Backpack(object):    #Part 1
    def __init__(self, name, color, max_size = 5):
        '''
        (part 4) object class. including a name, a color, and maximum size for contents and a content list.

        Attributes:
             name (string) : name of the backpack's owner.
             color (string) : color of the backpack.
             max_size (integer) : the maximum size of the backpack.
             contents (list) : contents of the backpack.
        '''
        self.name = name
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):    #part 2
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def dump(self):    #part 3
        self.contents = []

#-----------------------------------------------------------------
#-----------------------------------------------------------------
testpack = Backpack("Mahyar", "Blue")
for item in ["pen", "pencil", "notebook", "laptop", "mouse", "umbrella"]:
    testpack.put(item)
print("contents: ", testpack.contents)
# no room for "umbrella"!

No Room!
contents:  ['pen', 'pencil', 'notebook', 'laptop', 'mouse']


In [21]:
testpack.dump()
print("contents: ", testpack.contents)

contents:  []


## Problem 2

In [26]:
# Backpack object class, attributes and details are explained and constructed in previous lines in problem 1.
# First run Problem 1, Backpack class. 

########################################################################
########################################################################

class Jetpack(Backpack):
    """
    A Jetpack object class. Inherited from Backpack class.
    A Jetpack is smaller than a Backpackself.

    Attributes:
        name (str): the name of the Jetpack's owner.
        color (str): color of Jetpack
        max_size (int): maximum number of items that can be fit inside the Jetpack
        fuel (int):
        contents (list): the contents of the Jetpack
    """
    def __init__(self, name, color, max_size = 2, fuel =10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel

    def fly(self, burned_fuel):
        self.burned_fuel = burned_fuel
        if self.burned_fuel <= self.fuel:
            self.fuel = self.fuel - self.burned_fuel
        if self.burned_fuel > self.fuel:
            self.fuel = self.fuel
            print("Not Enough Fuel!")
    def dump(self):
        Backpack.dump(self)
        self.fuel = 0

In [27]:
test = Jetpack("Mahyar", "White")
test.put("calculator")
print(test.contents, test.fuel)

['calculator'] 10


In [28]:
test.dump()
print(test.contents, test.fuel)

[] 0


In [29]:
for item in ["pen", "pencil", "notebook"]:
    test.put(item)
print(test.contents, test.fuel)

No Room!
['pen', 'pencil'] 0


In [30]:
test.fly(1)
print(test.contents, test.fuel)

Not Enough Fuel!
['pen', 'pencil'] 0
