## Standard Library Questions
** Problem 1 **: Function that accepts  a list of numbers as input and returns a new list with the minimum, maximum and average of the original list (in that order). Remember to use floating point division to calculate the average. Can you implement this function in a single line?

In [6]:
# Part1: Function that returns a list of min, max and average
def function_p1a (list_num):
    """
    Function that takes in a list of numbers (list_num)
    """
    min_list=min(list_num)
    max_list=max(list_num)
    avg_list=round(sum(list_num)/len(list_num),2)
    list_out=[min_list,max_list,avg_list]
    return("The minimum, maximum and average of the list are:",list_out)

In [7]:
# Testing the above function on a sample list l1
l1=[1,2,2]
function_p1a(l1)

('The minimum, maximum and average of the list are:', [1, 2, 1.67])

In [9]:
# Part 2: Same function implemented in a single line
def function_p1b(list_num):
    """
    Function that takes in a list of numbers (list_num) and uses a single line of code
    """
    return("The minimum, maximum and average of the list are:",[min(list_num),max(list_num),round(sum(list_num)/len(list_num),2)])

In [10]:
# Testing the above function on the same sample list
function_p1b(l1)

('The minimum, maximum and average of the list are:', [1, 2, 1.67])

** Problem2 **: Determine which objects are mutable using the example given in the problem set

In [11]:
# Checking if integers are mutable
num_1=4
num_2=num_1
num_2+=1
num_1==num_2

False

In [12]:
# Checking if strings are mutable
string_1='Devashish'
string_2=string_1
string_2+=' Thakar'
string_1==string_2

False

In [13]:
# Checking if lists are mutable
list_1=['a','b','c']
list_2=list_1
list_2.append('d')
list_1==list_2

True

In [14]:
# Checking if tuples are mutable
tuple_1=(1,2,3,'a','b')
tuple_2=tuple_1
tuple_2+=('c',)
tuple_1==tuple_2

False

In [9]:
# Checking if a dictionary is mutable
dict_1={'First letter':'a','Second letter':'b','Third letter':'c'}
dict_2=dict_1
dict_2['Fourth letter']='d'
dict_1==dict_2

True

In [19]:
# Checking if a set is mutable
set_1={1,2,3,4,5}
set_2=set_1
set_2|={6,7,8,9,10}
set_1==set_2

True

**Based on the above outputs, it can be concluded that * numbers, strings &tuples * are immutable, while * lists, dictionaries & sets * are mutable **

** Problem 3 **: Creating a module with sum function, product function and square root function to create another function to return the length of hypoteneuse of a right angled triangle

The module I created is called calculator and have stored it as calculator.py, which I am importing below. It has the sum_calc function to calculate the sum, product_calc function to find the product, and sqrt_calc to find the square root

In [20]:
import calculator as calc
'''
The 'calculator' module consists of three functions that I have built.
product_calc: calculates the product of two numbers
sum_calc: calcuates the sum of two numbers
sqrt_calc: calculates the square root of a number

All three functions are used below to calculate the length of the hypotenuse
'''

"\nThe 'calculator' module consists of three functions that I have built.\nproduct_calc: calculates the product of two numbers\nsum_calc: calcuates the sum of two numbers\nsqrt_calc: calculates the square root of a number\n\nAll three functions are used below to calculate the length of the hypotenuse\n"

In [21]:
# Defining a new function to use the above functions to calculate the length of the hypotenuse of a right triangle
def hypotenuse_len(a,b): # Consider a,b to be the length of the other two sides of the hypotenuse
    '''
    a and b are the lenth of the shorter sides of the right angled triangle
    
    '''
    a_squared=calc.product_calc(a,a) # calling in the product_calc function to square a
    b_squared=calc.product_calc(b,b) # calling in the product_calc function to square b
    hyp=calc.sqrt_calc(calc.sum_calc(a_squared,b_squared))  # calling in the sum_calc and sqrt_calc to sum a^2, b^2 and find the square root
    return(hyp)
    

In [24]:
hypotenuse_len(3,4)

5.0

# NumPy questions


** Problem1 **: Write a function that defines A and B as NumPy arrays. Return product AB.

In [25]:
import numpy as np

def matrix_multiply(list1,list2):
    '''
    list1 and list2 are 'list of lists' that define matrix A and B
    
    The dot product of the matrices A and B is C
    '''
    import numpy as np
    
    A=np.array(list1)
    B=np.array(list2)
    C=np.dot(A,B)
    return C
    
    
    

In [26]:
x=[[3, -1, 4], [1, 5, -9]]
y=[[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]]
matrix_multiply(x,y)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

** Problem 2**: Function to do multiple operations on a given matrix

In [27]:
import numpy as np

def CH_Theorem(list3): # Naming this function afer Cayley-Hamilton(CH) Theorem
    '''
    A is the NumPy array created using the matrix defined from the input list
    '''
    A=np.array(list3)
    
    A_cube=np.dot(A,np.dot(A,A)) # Cube of A
    A_square=np.dot(A,A) # Square of A
    Return_matrix= -1*A_cube + 9*A_square - 15*A
    
    return Return_matrix

In [28]:
 CH_Theorem([[3,1,4],[1,5,9],[-5,3,1]]) # Calling the function defined above

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

** Problem 5: ** Use of NumPy stacking functions to create a block matrix

In [29]:
import numpy as np
def matrix_stacking(list1,list2,list3):
    
    '''
    Defining the basic matrices A, B and C
    '''
    A=np.array(list1)
    B=np.array(list2)
    C=np.array(list3)
    
    '''
    Defining the matrices required to do stacking operation 
    '''
    A_T=A.T # Transpose of A
    zero_11=np.zeros((A_T.shape[0],A.shape[1])) # The zero matrix at position 1x1
    I_13=np.eye(A_T.shape[0]) # The identity matrix at position 1x3
    zero_22=np.zeros((A.shape[0],A_T.shape[1])) # The zero matrix at position 2x2
    zero_23=np.zeros((A.shape[0],I_13.shape[1])) # The zero matrix at position 2x3
    zero_32=np.zeros((B.shape[0],A_T.shape[1]))# The zero matrix at position 3x2
    
    
    '''
    Creating the rows of the matrix using horizontal stacking
    '''
    Stack_1= np.hstack((zero_11,A_T,I_13)) # First row of the stacked matrix
    Stack_2=np.hstack((A,zero_22,zero_23)) # Second row of the stacked matrix
    Stack_3=np.hstack((B,zero_32,C)) # Third row of the stacked matrix
    
    '''
    Vertically stacking these rows to create the final stacked matrix
    '''
    Stack=np.vstack((Stack_1,Stack_2,Stack_3))
    
    return Stack


In [30]:
l1=[[0,2,4],[1,3,5]]
l2=[[3,0,0],[3,3,0],[3,3,3]]
l3=[[-2,0,0],[0,-2,0],[0,0,-2]]

matrix_stacking(l1,l2,l3)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

# Object Oriented Programming

** Problem 1**: Expanding the BackPack class as per the question specifications

In [40]:
class Backpack:
    """ A BackPack object class. Has a name,list of contents,color and maximum size.
    
    Attributes:
    name(str): the name of the backpack's owner
    contents(list): the contents of the backpack.
    color(str): the color of the backpack
    max_size(int): the maximum number of items that can be placed in the backpack
    
    Put(item): Method to add 'item' to the backpack
    If the number of 'item' in the backpack is greater than the 'max_size', 
    error message is displayed and no more items added. Otherwise the new 'item' is added to the backpack
    
    Take(item): Method to remove 'item' from the backpack
    
    dump(): Method to empty the backpack
    If this method is invoked then all the 'item' from the backpack are removed
    """
    
    
    def __init__(self, name, color,max_size=5): # This function is the constructor.
        """ Set the name and initialize te initial list of contents.
        
        Parameters:
        name(str): the name of the backpack's owner.
        """
        self.name=name                 # Initialize attributes
        self.color=color
        self.max_size=max_size
        self.contents=[]
        
    def put(self,item):
        '''
        Method to check if the number of items in the backpack is more than or equal to max_size. If yes, send out
        error message, if no, add the item to the backpack
        '''
        if len(self.contents)>self.max_size-1:
            
            print("Cannot accomodate all contents.Only the first", self.max_size ," can be considered. Sorry!")
            
        else:
            self.contents.append(item)  # use self.contents, not just contents
        
    def take(self,item):
        
        """ Method to remove an item from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """
        Removes all the contents of the backpack and make it empty
        """
        self.contents=[]

In [41]:
# Test function to check the various methods of the Backpack class
def test_backpack():
    testpack=Backpack("Barry","black")
    
    if testpack.name!="Barry":                            # Check if the name of the backpack is correct
        print("Backpack.name assignedincorrectly")
        
    for item in ["pencil","pen","paper",'torch','insects']:   # List of items to be put in the backpack
        testpack.put(item)
    print("These are the original contents you want to put:", testpack.contents)
    
    for item in testpack.contents:           # Taking out the item if it is "food"
        if item=="food":
            testpack.take("food")
            print("Sorry, food cannot be included. The remaining contents:",testpack.contents)
            
    for item in testpack.contents:          # Empytying the contents of the backpack if there are "insects"!
        if item=='insects':
            testpack.dump()
            print("Cannot have insects in the backpack! Have to empty all contents")
    print("Final Contents:",testpack.contents)

In [42]:
test_backpack()

These are the original contents you want to put: ['pencil', 'pen', 'paper', 'torch', 'insects']
Cannot have insects in the backpack! Have to empty all contents
Final Contents: []


** Problem 2 **: Creating a subclass that inherits the Backpack class

In [56]:
# Inherit from the Backpack class created above.
class Jetpack(Backpack):
    """ 
    A Jetpack object class. Inherits from the Backpack class.
    A Jetsack is smaller than a backpack that can also stores fuel
    
    Attributes:
        name(str): the name of the jetpack's owner
        color(str): the color of the jetpack
        max_size(int): the maximum number of items that can fit inside
        contents: the contents of the jetpack
        fuel= the amount of fuel in the jetpack
    """
    
    def __init__(self, name, color,max_size=2,fuel=10):
        
        """
        Use the Backpack constructor to initialize the name, color, and max_size attributes.
        A jetsack holds only upto 2 items
        
        Parameters: 
           name(str): the name of the jetpack's owner
           color(str): the color of the jetpack
           max_size(int): the maximum number of items that can fit inside 
        """
        
        Backpack.__init__(self,name,color,max_size)
        self.fuel=fuel                        # Set fuel as an attribute
        
    def fly(self,amt_burnt): # Define a new method fly() just for jetsack,which takes in the amt_burnt (as the amount of fuel burnt)
        """ 
        If the amt_burnt is less than the fuel available, then decrement the fuel burnt by that amount
        Else if the user tries to burn more fuel than available, then print error message
        """
        if amt_burnt<self.fuel:
            self.fuel=self.fuel-amt_burnt
            print("Fuel left after burning the amount you gave is:",self.fuel)
        else:
            print("Not enought fuel to burn!")
    
    def dump(self): # Override the dump method to empty both the contents and fuel in the jetsack
        self.contents=[]
        self.fuel=0
    

In [57]:
my_jetpack=Jetpack("Thakar","red")

In [58]:
# A jetpack is a backpack, but a backpack is not a jetpack
print(issubclass(Jetpack,Backpack),issubclass(Backpack,Jetpack))
isinstance(my_jetpack,Backpack) and isinstance(my_jetpack,Jetpack)

True False


True

In [59]:
# Check if the jetpack can hold the items that I pass through this function
def test_jetpack():
    jetpack=Jetpack("Devashish","blue")
    for item in ['pen','pencil','eraser']:
        jetpack.put(item)
        print(jetpack.contents)

In [60]:
# Putting it item by item untill I get a stop message and then checking the contenst
test_jetpack1=Jetpack("Devashish","maroon")
test_jetpack1.put("pen")
test_jetpack1.put("pencil")
test_jetpack1.put("eraser")
test_jetpack1.contents

Cannot accomodate all contents.Only the first 2  can be considered. Sorry!


['pen', 'pencil']

In [61]:
# Chekcing if the fuel burning method works
test_jetpack1.fly(2)  # I start with burning 10 gallons and see how many remain

Fuel left after burning the amount you gave is: 8


In [62]:
# Checking if it allows me to burn the remaining 8 gallons
test_jetpack1.fly(8)

Not enought fuel to burn!


In [63]:
# Checking the dump method. Before dumping we have the following items and fuel:
print("The following items were present before dumping:",test_jetpack1.contents)
print("The following amount of fuel was present before dumping:",test_jetpack1.fuel)

The following items were present before dumping: ['pen', 'pencil']
The following amount of fuel was present before dumping: 8


In [64]:
# After calling in the dump method, the following is the list of contents and amount of fuel:
test_jetpack1.dump()
print("The following items present after dumping:",test_jetpack1.contents)
print("The following amount of fuel is present after dumping:",test_jetpack1.fuel)

The following items present after dumping: []
The following amount of fuel is present after dumping: 0
