# Python Built-in Types
### September 3, 2019

There are 8 data types that are native to the base Python library:
1. Numeric (integers, floating point numbers)
2. Boolean
3. Strings
4. Lists
5. Set
6. Tuple
7. Dictionary
8. Range

## Numeric data

In [ ]:
three = 3

In [ ]:
three

In [ ]:
type(three)

In [ ]:
three = 3.0

In [ ]:
type(three)

In [ ]:
three = int(3.0)

In [ ]:
type(three)

In [ ]:
two = 2

In [ ]:
two * three

In [ ]:
two + three

## Boolean

In [ ]:
light = True
type(light)

In [ ]:
two + light  # math with booleans

In [ ]:
off = False
two + off

## Sequence Data types

### Strings

Strings are sequences of characters.  They are *immutable*  - they can't be changed after they are created.

In [ ]:
name = 'Jason'

In [ ]:
name[0]   # to take the first element

In [ ]:
name[4]  # to take the 5th element

In [ ]:
name[-1]  # to take the last element - no matter length

In [ ]:
name[1:3]  # this takes the 2nd and up to, but not including the 4th element

In [ ]:
name[-2]

In [ ]:
name[-2:]  # this takes the last two elements

In [ ]:
name[1:]  # this takes from the second element onwards

In [ ]:
name[:-1]  # this takes all but the last element

In [ ]:
for letter in name:  # to loop over letters in name
    print(letter)  # indented so it's in the loop

## Lists

Lists contain sequences of objects.  The objects can be of any type AND you can mix types.

In [ ]:
mylist = [1, 2, 3, 'a', 'b', 'c']  # square brackets define a list
print(mylist)

In [ ]:
mylist[0]

In [ ]:
mylist[1:]

In [ ]:
for item in mylist:
    print(item)

In [ ]:
num_list = [1, 2, 3]

In [ ]:
num_list * 2

In [ ]:
mylist * 2

In [ ]:
for item in num_list:
    print(item * 2)

## Tuple

Tuple is an ordered list.  It can contain mixed data types.  It differs from a list because it is *immutable*.  This means the elements of the tuple can't be changed after the tuple is created.

In [ ]:
mytuple = (1, 2, 3, 'a', 'b', 'c')
print(mytuple)

In [ ]:
mytuple_2 = (1, 2, 3, mylist)
print(mytuple_2)

In [ ]:
mytuple[0] = 4  # can't do this because the tuple is immutable!
print(mytuple)

In [ ]:
mylist[0] = 4  # can do this because the list is mutable
print(mylist)

In [ ]:
mytuple[1:]

In [ ]:
mytuple2 = (4, mytuple[1:])
print(mytuple2)

## Sets

Sets are sequeces of *unique* values.  Sequences are mutable like lists.

In [ ]:
myset = {1, 2, 3, 3, 4}
print(myset)

In [ ]:
mylist3 = [1, 2, 3, 3, 4]
print(mylist3)

In [ ]:
myset[0]  # can't access with index values

In [ ]:
myset2 = {2, 2, 5, 1, 8, 4}
print(myset2)

In [ ]:
for item in myset2:  # can iterate over sets
    print(item)

## Dictionary

A dictionary is set of key and value pairs.  So we reference a item in a dictionary with its key.

In [ ]:
address = {"Business name": "DMSB", "Street": "1014 Greene St.", "City": "Columbia", "zip": 29208}

In [ ]:
print(address)

In [ ]:
addresses = {"Business name": ["DMSB", "Wendy's"], "Street": ["1014 Greene St.", "1000 Assembly St."],
             "City": ["Columbia", "Columbia"], "zip": [29208, 29208]}
print(addresses)

In [ ]:
addresses['Business name']  # reference an element by it's key

In [ ]:
addresses[0]

In [ ]:
# Iterating over lists give us a couple options
for v in addresses.values():  # iterate over values
    print(v)

In [ ]:
for k in addresses.keys():  # iterate over values
    print(k)

In [ ]:
for k, v in addresses.items(): # iterate over keys and values
    print('key = ', k)
    print('value = ', v)

In [ ]:
addresses.keys()

## Range

A range of values.  Ranges are *immutable*.

In [ ]:
nums = range(0, 3)
print(nums)

In [ ]:
for i in nums:  # print out the items in the range
    print(i)

# Numpy

`Numpy` is a package that allows for array operations + many other math functions.

In [1]:
import numpy as np  # import numpy and give it an alias that is np

In [2]:
# The basic data structure is the Numpy array
A = np.array([3, 5])
print(A)

[3 5]


In [3]:
A * 2

array([ 6, 10])

In [4]:
A * A  # element-by-element multiplication

array([ 9, 25])

In [5]:
type(A)

numpy.ndarray

In [6]:
B = np.array([[3, 5], [4, 6]])
print(B)

[[3 5]
 [4 6]]


In [7]:
B.shape

(2, 2)

In [8]:
B.size

4

In [9]:
A.shape

(2,)

In [10]:
B * A  # element-by-element multiplication - with some "broadcasting"

array([[ 9, 25],
       [12, 30]])

In [11]:
C = np.array([7, 8, 9])
print(C)

[7 8 9]


In [12]:
B * C  # a 2x2 matrix times a lenght 3 vector...

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [13]:
np.dot(B, A)

array([34, 42])

In [14]:
D = np.array([-1, 2, 4])
np.absolute(D)

array([1, 2, 4])

In [15]:
np.max(D)

4

In [16]:
np.min(D)

-1

In [17]:
A[:]

array([3, 5])

In [18]:
A[1:]

array([5])

In [19]:
B[0, 1]

5

In [20]:
B[1, 0]

4

In [21]:
B[0, :]

array([3, 5])

In [22]:
type(B)

numpy.ndarray

In [23]:
A * B

array([[ 9, 25],
       [12, 30]])

In [24]:
B * A

array([[ 9, 25],
       [12, 30]])

In [25]:
C

array([7, 8, 9])

In [26]:
B.shape

(2, 2)

In [27]:
# Reshape arrays
B.T  #transpose

array([[3, 4],
       [5, 6]])

In [29]:
B.reshape((4, 1))

array([[3],
       [5],
       [4],
       [6]])

### Special arrays in Numpy

These include arrays of all zeros, all ones, arrays of a size like something else, or an identity matrix

In [30]:
justones = np.ones((4, 2, 3))
justones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
justzero = np.zeros((3, 2))
justzero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [35]:
E = np.zeros_like(B)
E

array([[0, 0],
       [0, 0]])