# Python Built-in Types

There are 8 data types that are native to the base Python library:
1. Numeric (integers, floating point numbers)
2. Boolean
3. Strings
4. Lists
5. Set
6. Tuple
7. Dictionary
8. Range

## Numeric data

In [98]:
three = 3

In [99]:
three

3

In [3]:
type(three)

int

In [4]:
three = 3.0

In [5]:
type(three)

float

In [6]:
three = int(3.0)

In [7]:
type(three)

int

In [8]:
two = 2

In [9]:
two * three

6

In [10]:
two + three

5

## Boolean

In [11]:
light = True
type(light)

bool

In [12]:
two + light  # math with booleans

3

In [13]:
off = False
two + off

2

## Sequence Data types

### Strings

Strings are sequences of characters.  They are *immutable*  - they can't be changed after they are created.

In [17]:
name = 'Jason'

In [18]:
name[0]   # to take the first element

'J'

In [19]:
name[4]  # to take the 5th element

'n'

In [20]:
name[-1]  # to take the last element - no matter length

'n'

In [22]:
name[1:3]  # this takes the 2nd and up to, but not including the 4th element

'as'

In [23]:
name[-2]

'o'

In [24]:
name[-2:]  # this takes the last two elements

'on'

In [25]:
name[1:]  # this takes from the second element onwards

'ason'

In [26]:
name[:-1]  # this takes all but the last element

'Jaso'

In [27]:
for letter in name:  # to loop over letters in name
    print(letter)  # indented so it's in the loop

J
a
s
o
n


## Lists

Lists contain sequences of objects.  The objects can be of any type AND you can mix types.

In [28]:
mylist = [1, 2, 3, 'a', 'b', 'c']  # square brackets define a list
print(mylist)

[1, 2, 3, 'a', 'b', 'c']


In [29]:
mylist[0]

1

In [30]:
mylist[1:]

[2, 3, 'a', 'b', 'c']

In [31]:
for item in mylist:
    print(item)

1
2
3
a
b
c


In [32]:
num_list = [1, 2, 3]

In [33]:
num_list * 2

[1, 2, 3, 1, 2, 3]

In [34]:
mylist * 2

[1, 2, 3, 'a', 'b', 'c', 1, 2, 3, 'a', 'b', 'c']

In [35]:
for item in num_list:
    print(item * 2)

2
4
6


## Tuple

Tuple is an ordered list.  It can contain mixed data types.  It differs from a list because it is *immutable*.  This means the elements of the tuple can't be changed after the tuple is created.

In [37]:
mytuple = (1, 2, 3, 'a', 'b', 'c')
print(mytuple)

(1, 2, 3, 'a', 'b', 'c')


In [39]:
mytuple_2 = (1, 2, 3, mylist)
print(mytuple_2)

(1, 2, 3, [1, 2, 3, 'a', 'b', 'c'])


In [40]:
mytuple[0] = 4  # can't do this because the tuple is immutable!
print(mytuple)

TypeError: 'tuple' object does not support item assignment

In [41]:
mylist[0] = 4  # can do this because the list is mutable
print(mylist)

[4, 2, 3, 'a', 'b', 'c']


In [43]:
mytuple[1:]

(2, 3, 'a', 'b', 'c')

In [45]:
mytuple2 = (4, mytuple[1:])
print(mytuple2)

(4, (2, 3, 'a', 'b', 'c'))


## Sets

Sets are sequeces of *unique* values.  Sequences are mutable like lists.

In [49]:
myset = {1, 2, 3, 3, 4}
print(myset)

{1, 2, 3, 4}


In [50]:
mylist3 = [1, 2, 3, 3, 4]
print(mylist3)

[1, 2, 3, 3, 4]


In [51]:
myset[0]  # can't access with index values

TypeError: 'set' object is not subscriptable

In [52]:
myset2 = {2, 2, 5, 1, 8, 4}
print(myset2)

{1, 2, 4, 5, 8}


In [53]:
for item in myset2:  # can iterate over sets
    print(item)

1
2
4
5
8


## Dictionary

A dictionary is set of key and value pairs.  So we reference a item in a dictionary with its key.

In [54]:
address = {"Business name": "DMSB", "Street": "1014 Greene St.", "City": "Columbia", "zip": 29208}

In [55]:
print(address)

{'Business name': 'DMSB', 'Street': '1014 Greene St.', 'City': 'Columbia', 'zip': 29208}


In [56]:
addresses = {"Business name": ["DMSB", "Wendy's"], "Street": ["1014 Greene St.", "1000 Assembly St."],
             "City": ["Columbia", "Columbia"], "zip": [29208, 29208]}
print(addresses)

{'Business name': ['DMSB', "Wendy's"], 'Street': ['1014 Greene St.', '1000 Assembly St.'], 'City': ['Columbia', 'Columbia'], 'zip': [29208, 29208]}


In [58]:
addresses['Business name']  # reference an element by it's key

['DMSB', "Wendy's"]

In [59]:
addresses[0]

KeyError: 0

In [61]:
# Iterating over lists give us a couple options
for v in addresses.values():  # iterate over values
    print(v)

['DMSB', "Wendy's"]
['1014 Greene St.', '1000 Assembly St.']
['Columbia', 'Columbia']
[29208, 29208]


In [63]:
for k in addresses.keys():  # iterate over values
    print(k)

Business name
Street
City
zip


In [64]:
for k, v in addresses.items(): # iterate over keys and values
    print('key = ', k)
    print('value = ', v)

key =  Business name
value =  ['DMSB', "Wendy's"]
key =  Street
value =  ['1014 Greene St.', '1000 Assembly St.']
key =  City
value =  ['Columbia', 'Columbia']
key =  zip
value =  [29208, 29208]


In [65]:
addresses.keys()

dict_keys(['Business name', 'Street', 'City', 'zip'])

## Range

A range of values.  Ranges are *immutable*.

In [67]:
nums = range(0, 3)
print(nums)

range(0, 3)


In [68]:
for i in nums:  # print out the items in the range
    print(i)

0
1
2


# Numpy

`Numpy` is a package that allows for array operations + some many other math functions.

In [71]:
import numpy as np  # import numpy and give it an alias that is np

In [73]:
# The basic data structure is the Numpy array
A = np.array([3, 5])
print(A)

[3 5]


In [74]:
A * 2

array([ 6, 10])

In [76]:
A * A  # element-by-element multiplication

array([ 9, 25])

In [77]:
type(A)

numpy.ndarray

In [79]:
B = np.array([[3, 5], [4, 6]])
print(B)

[[3 5]
 [4 6]]


In [80]:
B.shape

(2, 2)

In [81]:
B.size

4

In [82]:
A.shape

(2,)

In [83]:
B * A  # element-by-element multiplication - with some "broadcasting"

array([[ 9, 25],
       [12, 30]])

In [84]:
C = np.array([7, 8, 9])
print(C)

[7 8 9]


In [85]:
B * C  # a 2x2 matrix times a lenght 3 vector...

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [86]:
np.dot(B, A)

array([34, 42])

In [87]:
D = np.array([-1, 2, 4])
np.absolute(D)

array([1, 2, 4])

In [88]:
np.max(D)

4

In [89]:
np.min(D)

-1

In [90]:
A[:]

array([3, 5])

In [91]:
A[1:]

array([5])

In [92]:
B[0, 1]

5

In [93]:
B[1, 0]

4

In [94]:
B[0, :]

array([3, 5])

In [95]:
type(B)

numpy.ndarray